name: SimpleTimer
version: '${version}'
main: com.spectrasonic.SimpleTimer.Main
api-version: '1.21'
authors: [ Spectrasonic ]
description: A Simple Timer for Minecraft Events
commands:
  timer:
    description: Start a timer with a bossbar.
    usage: /timer <time><h/m/s> <title> <color>
    aliases: [tm]