name: SimpleTimer
version: '1.0.2-1.20.4'
main: com.spectrasonic.SimpleTimer.Main
api-version: '1.20'
authors: [ Spectrasonic ]
description: A Simple Timer for Minecraft Events
commands:
  timer:
    description: Start a timer with a bossbar.
    usage: /timer <time><h/m/s> <title> <color>
    aliases: [tm]